nypublicradio/wnyc-web-client

- app/components/site-chrome/template.hbs
- app/services/bumper-state.js
- config/environment.js
- tests/acceptance/settings-authenticated-test.js
- tests/unit/services/audio-test.js
- tests/unit/services/bumper-state-test.js
https://jira.wnyc.org/browse/WE-6595
> Enable continuous play (Remove google experiment)

- app/styles/legacy/_home-compat.scss
https://jira.wnyc.org/browse/WE-6529
> WE-6529 Lightly refreshes homepage feel.

- app/styles/_player-notification.scss
- app/styles/_site-chrome.scss
- app/styles/_vars.scss
https://jira.wnyc.org/browse/WE-6602
> WE-6602 Tightens up autoplay notification bar 

- app/discover/edit/template.hbs
- app/styles/_discover.scss
- mirage/scenarios/default.js
Some weird wrapping happens when browser window is sized down to $medium. Also made dev environment show actual topics instead of randomly generated ones
> Fix button wrapping and title alignment on setup screens for discover

- app/controllers/profile.js
- app/templates/profile.hbs
- package.json
- tests/acceptance/profile-test.js
[ticket](https://jira.wnyc.org/browse/WE-6585)
> Password editing and error states

- app/components/user-navigation/template.hbs
ember simple auth syncs between window for free, so we can just open these auth pages in a new window.
> open login and signup in new windows

- app/components/account-signup-form/component.js
[ticket](https://jira.wnyc.org/browse/WE-6708)
> clear confirmationEmail values and errors on duplicate email error

- app/components/account-login-form/component.js
https://jira.wnyc.org/browse/WE-6506
> Update error message for non-matching username and password

- app/components/account-validation-form/component.js
- app/components/account-validation-form/template.hbs
https://jira.wnyc.org/browse/WE-6816
> Don't show flash of Oops page on email validation

- app/validations/custom-messages.js
- app/validations/signup.js
https://jira.wnyc.org/browse/WE-6710
> WE-6710 Add validations for leading and trailing spaces on names

- app/components/user-navigation/template.hbs
- app/templates/application.hbs
* Don't open login in a new window
* Don't hide the player on the login screen
* Do hide the round queue button if nothing is playing
https://jira.wnyc.org/browse/WE-6805
> WE-6805 Show player on login

- app/components/account-thanks/template.hbs
Let the user know it may take a few minutes, so they don't try resend right away.
https://jira.wnyc.org/browse/WE-6770
> WE-6770 Update check your email message

- app/components/site-chrome/site-footer/template.hbs
- mirage/helpers/django-html.js
https://jira.wnyc.org/browse/WE-6811
> fix footer link issue for listener services [WE-6811]

- app/components/site-chrome/template.hbs
- app/story/template.hbs
- app/styles/_simple-callout.scss
- app/styles/_site-chrome.scss
https://jira.wnyc.org/browse/WE-6675
> Remove discover promos [WE-6675]

- app/components/comments-form/component.js
- app/services/data-pipeline.js
- tests/unit/services/data-pipeline-test.js
- send comments to internal: [WE-6850](https://jira.wnyc.org/browse/WE-6850)
- fix delta calculations: [STATS-353](https://jira.wnyc.org/browse/STATS-353)
> Misc fixes

- app/stream/serializer.js
- mirage/factories/stream.js
- tests/unit/services/audio-test.js
First phase of [this ticket](https://jira.wnyc.org/browse/STATS-361)
> New Fieldname for MP3 Streams

- app/styles/_user-navigation.scss
https://jira.wnyc.org/browse/WE-6575
> WE-6575 Add new fullscreen menu style for user menu

- app/components/user-navigation/template.hbs
https://jira.wnyc.org/browse/WE-6794
Note: need to update settings link here after #64 is merged (or in #64 after this is merged)
> WE-6794 Close user menu popup on link click 

- app/components/account-wrapper/component.js
- app/styles/_accounts.scss
https://jira.wnyc.org/browse/WE-6827
> WE-6827 Tweak account template when player is open

- app/authenticators/torii.js
- app/authorizers/nypr.js
- app/components/account-login-form/component.js
- app/components/account-login-form/template.hbs
- app/components/account-signup-form/component.js
- app/components/account-signup-form/template.hbs
- app/routes/signup.js
- app/styles/_accounts.scss
- app/templates/signup.hbs
- app/torii-providers/facebook-connect.js
- app/user/adapter.js
- app/user/model.js
- app/user/serializer.js
- app/validations/custom-messages.js
- config/environment.js
- mirage/config.js
- mirage/scenarios/default.js
- package.json
- tests/acceptance/login-test.js
- tests/acceptance/reset-test.js
- tests/acceptance/signup-test.js
- tests/acceptance/validate-test.js
- tests/integration/components/account-login-form/component-test.js
Client side updates for creating an account using facebook
> Social auth

- app/components/account-signup-form/template.hbs
https://jira.wnyc.org/browse/WE-6997
> Fix missing sign up header

- app/components/site-chrome/site-footer/template.hbs
https://jira.wnyc.org/browse/WE-6946
> Update footer copy

- app/components/player-notification/autoplay-message/template.hbs
- app/controllers/application.js
- app/styles/_player-notification.scss
- app/templates/application.hbs
- tests/integration/components/player-notification/autoplay-message/component-test.js
https://jira.wnyc.org/browse/WE-6763
> Make 'change settings' link depend on login state

- app/channel/model.js
- app/channel/template.hbs
- app/components/alt-channel-layout/template.hbs
- app/components/listen-button/embedded/component.js
- app/models/django-page.js
[ticket](https://jira.wnyc.org/browse/WE-7078)
> Render embedded components in channel teases

- app/helpers/song-metadata.js
- tests/integration/components/nypr-player-integration/component-test.js
- tests/integration/components/stream-banner-test.js
- tests/unit/helpers/song-metadata-test.js
mirror of nypublicradio/wqxr-web-client#21
> Song metadata updates

- app/styles/_nypr-player-overrides.scss
- app/styles/_usersettings.scss
[WE-7005](https://jira.wnyc.org/browse/WE-7005)
don't import nypr-ui
scope usersettings css
> more settings drop down fixes

- app/styles/_player-notification.scss
https://jira.wnyc.org/browse/WE-6859
> WE-6859 Update notification link style

- app/controllers/profile.js
We need to do this so the form can show the error from the server
> pass error response along when changing password

- app/channel/template.hbs
- app/shows/template.hbs
- app/stream/template.hbs
- app/templates/index.hbs
also ads leaderboards to ember templates
> use breakpoints for leaderboard ads

- app/channel/route.js
- app/playlist/route.js
- app/routes/djangorendered.js
- app/routes/index.js
- app/schedule/date/route.js
- app/shows/route.js
- app/stream/route.js
- tests/acceptance/djangorendered-test.js
- tests/acceptance/home-test.js
- tests/acceptance/playlist-test.js
- tests/acceptance/schedule-test.js
- tests/acceptance/shows-test.js
- tests/acceptance/streams-test.js
- tests/acceptance/viewing-show-test.js
[WE-7302](https://jira.wnyc.org/browse/WE-7302)
moves some homepage specific tests into their own test
> do DFP targeting on most routes

- app/playlist/route.js
[WE-7311](https://jira.wnyc.org/browse/WE-7311)
> use correct model attribute for title on playlist route

- app/styles/_accounts.scss
- app/templates/profile.hbs
https://jira.wnyc.org/browse/WE-7266
> WE-7266 Show avatar, and don't let it distort

- app/controllers/profile.js
- app/routes/profile.js
- app/templates/profile.hbs
- mirage/config.js
- package.json
- tests/acceptance/profile-test.js
- tests/unit/controllers/profile-test.js
- yarn.lock
When a user visits the profile page, check the status of their email address against the membership API and set a property on the basic-card component based on this status.
> WE-7192 email pending verification message

- app/controllers/profile.js
- app/controllers/verify.js
- app/router.js
- app/routes/verify.js
- app/templates/verify.hbs
- mirage/config.js
- tests/acceptance/verify-test.js
- yarn.lock
https://jira.wnyc.org/browse/WE-7030
> Add /verify route

- app/channel/route.js
- app/channel/template.hbs
- app/chunk/adapter.js
- app/chunk/model.js
- app/chunk/serializer.js
- app/components/channel-header/template.hbs
- app/components/x-marquee/template.hbs
- app/lib/alien-dom.js
- mirage/config.js
- mirage/factories/chunk.js
- mirage/models/chunk.js
- tests/acceptance/viewing-show-test.js
- tests/unit/chunk/adapter-test.js
- tests/unit/chunk/model-test.js
- tests/unit/chunk/serializer-test.js
[WE-7364](https://jira.wnyc.org/browse/WE-7364)
> support listen live chunk on wnyc

- app/templates/profile.hbs
https://jira.wnyc.org/browse/NPL-1052
> Updated zendesk contact link in profile footer

- app/styles/_print.scss
- bower.json
- ember-cli-build.js
updates jquery migrate and cleans up some whitespace
> prep for wnyc template sweep

- app/authenticators/torii.js
- tests/acceptance/login-test.js
- tests/acceptance/signup-test.js
- yarn.lock
https://jira.wnyc.org/browse/WE-7222
Show an error message when email permissions are denied
> WE-7222 email permission denied

- app/styles/app.scss
- yarn.lock
needs https://github.com/nypublicradio/nypr-account-settings/pull/31
> Add account modal style import

- tests/acceptance/login-test.js
- yarn.lock
Test for https://github.com/nypublicradio/nypr-account-settings/pull/30
> WE-7224 Add test for social no password login error

- app/styles/_text.scss
- app/templates/profile.hbs
https://jira.wnyc.org/browse/WE-6855
> WE-6855 Don't let the contact number line wrap

- tests/acceptance/login-test.js
- yarn.lock
Test for nypublicradio/nypr-account-settings#39
https://jira.wnyc.org/browse/WE-7239
> WE-7239 Move error for non-existent email

- app/controllers/profile.js
- app/controllers/verify.js
- config/environment.js
- yarn.lock
https://jira.wnyc.org/browse/WE-7463
> WE-7463 Add timeout to flash messages

- app/controllers/set-password.js
- app/templates/set-password.hbs
- tests/acceptance/set-password-test.js
- yarn.lock
[WE-7524](https://jira.wnyc.org/browse/WE-7524)
> claim emails with membership on /set-password

- app/styles/_accounts.scss
- app/styles/_user-navigation.scss
- yarn.lock
https://jira.wnyc.org/browse/WE-7509
> WE-7509 Add min-height to avatar images so they scale properly in ie11

- app/templates/profile.hbs
- tests/acceptance/profile-test.js
- yarn.lock
Show the manage connection link if the account has an associated facebook id.
https://jira.wnyc.org/browse/WE-6871
> WE-6871 manage connection

- app/controllers/profile.js
- app/templates/profile.hbs
- mirage/config.js
- mirage/factories/user.js
- tests/acceptance/profile-test.js
- yarn.lock
https://jira.wnyc.org/browse/WE-7528
> WE-7528 password prompt when a facebook user needs to resend verify email

- app/routes/application.js
- tests/acceptance/missing-test.js
- tests/unit/routes/missing-test.js
- yarn.lock
https://jira.wnyc.org/browse/WE-7753
> WE-7753 Handle 404s

- app/channel/route.js
- app/story/route.js
- config/environment.js
- tests/acceptance/data-layer-test.js
https://jira.wnyc.org/browse/GT-112
> Add show title to data layer

- app/channel/route.js
- yarn.lock
Depends on https://github.com/nypublicradio/nypr-publisher-lib/pull/7
Redirects on the channel route when the channel url's host doesn't match the current host.
https://jira.wnyc.org/browse/GT-356
> GT-356 redirects

- config/environment.js
- package.json
- yarn.lock
[ticket](https://jira.wnyc.org/browse/RT-288)
> adds hotjar

- app/controllers/signup.js
- app/templates/signup.hbs
- package.json
- tests/acceptance/signup-test.js
- yarn.lock
Pre-fills account creation (signup) forms with e-mail address, first, and last name from query string in url. This url is intended to be shared in mailchimp to allow easy signup. 
https://jira.wnyc.org/browse/BT-172
> Signup prefill

- app/styles/_story.scss
- package.json
- yarn.lock
[ticket](https://jira.wnyc.org/browse/RT-360)
This implements the `pull-quote` mixin from nypublicradio/nypr-ui@465e5af for `.nypr-pull-quote` classes.
> Use pull quote mixin

- app/components/site-chrome/site-footer/template.hbs
- app/styles/_site-chrome.scss
[ticket](https://jira.wnyc.org/browse/RT-429)
> Adds EEO Link

- app/styles/_story.scss
- app/templates/full-bleed.hbs
For tickets [RT-365](https://jira.wnyc.org/browse/RT-365), [RT-408](https://jira.wnyc.org/browse/RT-408) and [RT-394](https://jira.wnyc.org/browse/RT-394).
> Full Bleed template tweaks

- app/story/route.js
- tests/acceptance/data-layer-test.js
[ticket](https://jira.wnyc.org/browse/RT-460)
Depends on the RT-460 workspace in GTM
> add `storyTemplate` to dataLayer

- app/components/site-chrome/template.hbs
- app/routes/application.js
- app/story/route.js
- app/styles/_discover.scss
- app/styles/_site-chrome.scss
- app/styles/app.scss
- app/templates/application.hbs
- config/environment.js
- mirage/config.js
- package.json
- yarn.lock
Currently failing due to a variety of errors not directly related with this work, including but not limited to an ember-responsive upgrade on audio-services.
> NYPR Brand Header

- app/styles/app.scss
- app/templates/index.hbs
> remove support stripe

- app/templates/index.hbs
[ticket](https://jira.wnyc.org/browse/RT-770)
> add 970 x 250 ad unit to homepage

- app/styles/_story.scss
jira: https://jira.wnyc.org/browse/RT-821
> Commit to add styling for block quote

- .env.sample
- app/components/site-chrome/template.hbs
- app/controllers/application.js
- app/styles/app.scss
- app/templates/application.hbs
- config/environment.js
- ember-cli-build.js
- mirage/config.js
- package.json
- yarn.lock
the election countdown has some fuzzy dependencies that are not added by the addon. it's important to note that using it in the web client requires:
- adding the `include-media` path to `sassOptions`
- configuring moment to include all timezones
> adds election countdown component

- app/routes/index.js
- app/styles/_stream-widget.scss
- app/styles/_utilities.scss
- app/templates/index.hbs
- package.json
- tests/acceptance/reset-test.js
- yarn.lock
...rather than isWNYC to better handle special streams, as streams will either be alwaysBroadcasting or have an airing tied to some CMS object
> use liveWNYC property in streambanner options

- package.json
- tests/acceptance/data-layer-test.js
- yarn.lock
> add container slug to data layer

- app/components/site-chrome/template.hbs
- package.json
- yarn.lock
This reverts commit b592df02ab98473375dafcb113f86f20469185f9.
> Re-add global election promo

- package.json
- yarn.lock
- Test build for new version of nypr-account-settings
> Test nypr-account-settings

- app/routes/profile.js
- package.json
- tests/acceptance/profile-test.js
- yarn.lock
Paired with https://github.com/nypublicradio/nypr-account-settings/pull/98.
https://jira.wnyc.org/browse/PAYMT-43
> Catch 500 error on orders API + failing message test

- app/components/site-chrome/component.js
- app/components/site-chrome/site-footer/template.hbs
https://nypublicradio-digital.atlassian.net/browse/DS-958
> Remove tumblr links from wnyc left nav and bottom nav

- app/components/site-chrome/site-footer/template.hbs
https://nypublicradio-digital.atlassian.net/browse/DS-1034
> Remove dead twitter links and snapchat

- app/templates/profile.hbs
https://nypublicradio-digital.atlassian.net/browse/SUP-6252
> Update profile page messaging

- app/channel/template.hbs
- app/schedule/date/template.hbs
- app/show/template.hbs
- app/story/template.hbs
- app/stream/template.hbs
- app/templates/index.hbs
- mirage/helpers/django-html.js
https://nypublicradio-digital.atlassian.net/browse/WNYC-10
Update ad manager ID and unit names across WNYC.
> WNYC-10 Update ad units

- app/templates/profile.hbs
Originally missed merging this slight change into the main branch. The change was a simple URL replacement and removal of unused Zendesk script.
> Removed Zendesk script and updated Contact URL.

- app/components/site-chrome/site-footer/template.hbs
- public/ads.txt
Created ads.txt to include Adswizz reference + added Online Member Services link.
> Created ads.txt and footer update

- config/environment.js
https://nypublicradio-digital.atlassian.net/browse/MEM-91
I only changed the donate link on line 82 - the rest is formatting noise!
> update donate link

- package.json
- yarn.lock
https://nypublicradio-digital.atlassian.net/browse/WNYC-45
> WNYC-45 add Transcript links

- app/components/user-navigation/template.hbs
- app/styles/_user-navigation.scss
- package.json
- tests/acceptance/login-test.js
- tests/integration/components/user-navigation/component-test.js
- yarn.lock
https://nypublicradio-digital.atlassian.net/browse/MEM-131
> Replace login/signup links with member center links 

- app/components/site-chrome/site-footer/template.hbs
- app/components/user-navigation/template.hbs
URL change to a new Springboard feature
> Member Center URL change

- app/components/centennial/centennial-archives/template.hbs
- app/components/centennial/centennial-card/template.hbs
- app/components/centennial/centennial-explore/template.hbs
- app/components/centennial/centennial-header/template.hbs
- app/components/centennial/centennial-intro/template.hbs
- app/components/centennial/centennial-share-button/component.js
- app/components/centennial/centennial-share-button/template.hbs
- app/components/centennial/centennial-timeline/template.hbs
- app/components/centennial/centennial-toggletip/component.js
- app/components/centennial/centennial-toggletip/template.hbs
- app/routes/centennial.js
- app/styles/_centennial.scss
- app/templates/centennial.hbs
- tests/integration/components/centennial/centennial-share-button/component-test.js
- tests/integration/components/centennial/centennial-toggletip/component-test.js
Archives
https://nypublicradio-digital.atlassian.net/browse/FE-74
Featured Centennial Content
https://nypublicradio-digital.atlassian.net/browse/FE-76
> Centennial Content Sections

- app/components/centennial/centennial-events/template.hbs
- app/components/centennial/event-card/component.js
- app/components/centennial/event-card/template.hbs
- app/routes/centennial.js
- app/styles/_centennial.scss
- app/templates/centennial.hbs
- tests/integration/components/centennial/event-card/component-test.js
https://nypublicradio-digital.atlassian.net/browse/FE-75
> FE-75 Centennial Events

- app/components/centennial/centennial-message/template.hbs
- app/styles/_centennial.scss
- app/templates/centennial.hbs
https://nypublicradio-digital.atlassian.net/browse/FE-72
> FE-72 Centennial Video Message

- app/components/centennial/centennial-cta-narrow/component.js
- app/components/centennial/centennial-cta-narrow/template.hbs
- app/styles/_centennial.scss
- app/templates/centennial.hbs
- tests/integration/components/centennial/centennial-cta-narrow/component-test.js
https://nypublicradio-digital.atlassian.net/browse/FE-79
> FE-79 Narrow Donation CTA

- app/components/centennial/centennial-legacy-giving/template.hbs
- app/styles/centennial/_centennial-base.scss
- app/styles/centennial/_centennial-cta-narrow.scss
- app/styles/centennial/_centennial-legacy-giving.scss
- app/templates/centennial.hbs
https://nypublicradio-digital.atlassian.net/browse/FE-139
> FE-139 Reorder centennial page

- app/components/centennial/centennial-message/template.hbs
- app/styles/centennial/_centennial-message.scss
https://nypublicradio-digital.atlassian.net/browse/FE-141
> FE-141 Update blurb next to centennial video message

- app/components/centennial/centennial-nav/template.hbs
- app/templates/centennial.hbs
https://nypublicradio-digital.atlassian.net/browse/FE-152
> Move stories section
