nypublicradio/wnyc-web-client

app/components/persistent-player/notification/template.hbs, app/styles/_player-notification.scss, tests/integration/components/persistent-player/notification/component-test.js
Move change settings link to be in the same line of text as the rest of the continuous play notification.  This should handle things like people who use smaller phones or larger font sizes better.
Also tweaked the margins of notification bar a bit to line up with player elements better. e.g. dismiss button  lined up with queue button.
https://jira.wnyc.org/browse/WE-6593
=> WE 6593 continuous play banner

app/authenticators/nypr.js, app/components/account-reset-password-form/component.js, app/components/account-signup-form/component.js, app/routes/application.js, app/services/current-user.js, app/user/adapter.js, config/environment.js, mirage/config.js, tests/acceptance/settings-authenticated-test.js, tests/acceptance/viewing-show-test.js, tests/acceptance/viewing-story-test.js, tests/integration/components/account-reset-password-form/component-test.js
@walsh9, please take a look at this ticket for some updates related to auth service compatibility. 
Also take a look at the `load` method in the `current-user` service. I'm setting `user` as the promise returned by the store, so that in templates, we can do `currentUser.user` and ember will resolve know how to resolve the value. 
This might make for some hiccups when dealing with `currentUser.user` in JS code since the value will always need to be accessed via `Promise.resolve`, but since the `user` is itself a globally available value via the service, other parts of the app can't reliably `.then` off of it, AFAIK.
=> auth service compat

tests/acceptance/streams-test.js
there was a bug in the audio service, expecting a previous audio object
to be present
=> adds failing test for playing a stream from cold start

app/channel/route.js, app/story/route.js
fixes story page and channel page legacy JS from working on
even-numbered visits due to unremoved listeners
=> adds beforeTeardown to story route's willTransition hook

app/channel/route.js, app/components/site-chrome/template.hbs, app/instance-initializers/link-handler.js, app/lib/compat-hooks.js, app/lib/is-js.js, app/routes/index.js, app/services/raven.js, app/styles/_animations.scss, tests/acceptance/viewing-show-test.js
Updates for better legacy compat. Depends on nypublicradio/publisher#6.
=> Legacy Cleanup

app/api-response/model.js, app/channel/model.js, app/channel/template.hbs, app/components/about-page/template.hbs, app/components/loading-templates/channel-page/template.hbs, app/components/loading-templates/component.js, app/components/story-detail/template.hbs, tests/acceptance/viewing-show-test.js
This PR updates how channel sub-pages are rendered so that if any arbitrary javascript is found in the text, the web client will parse and properly execute them.
now, this opens us up to potential bad UX cases if our pages start adding event listeners from server-side JS. ember won't have a way to know if these things are piling up, but let's see how this works in the wild.
=> Channel scripts

app/components/persistent-player/audio-metadata/component.js, app/components/persistent-player/center/template.hbs, app/services/audio.js, app/stream/serializer.js, tests/integration/components/audio-metadata/component-test.js
only send it if it's changed from the previous fire and if it's playing
[ticket](https://jira.wnyc.org/browse/WE-6756)
=> send Streamed Show event when show changes

.env.sample, app/channel/route.js, app/channel/template.hbs, app/components/channel-header/template.hbs, app/components/comments-admin/component.js, app/components/comments-admin/template.hbs, app/components/comments-form/component.js, app/components/comments-form/template.hbs, app/components/comments-list/template.hbs, app/components/django-page/component.js, app/components/story-comments/template.hbs, app/components/story-list/component.js, app/components/story-list/template.hbs, app/components/story-tease/template.hbs, app/components/x-marquee/template.hbs, app/metrics-adapters/data-warehouse.js, app/mixins/legacy-support.js, app/routes/application.js, app/services/listen-actions.js, app/services/session.js, app/story/route.js, app/story/template.hbs, circle.yml, config/environment.js, mirage/config.js, tests/acceptance/viewing-show-test.js, tests/acceptance/viewing-story-test.js
[ticket](https://jira.wnyc.org/browse/WE-6689)
This adds a staff auth method to the session service so that users who have authenticated against the publisher admin can still see admin controls via the web client.
*note* this does not require the user to be authenticated cognito or the `currentUser` service. These are separate authentication systems and so they don't really relate to or rely upon one another.
This also includes some other small clean ups in code that was geographically nearby the code I was working on.
=> Staff Auth Compat

app/controllers/profile.js, app/services/session.js, tests/acceptance/profile-test.js
[ticket](https://jira.wnyc.org/browse/WE-6728)
This PR works in concert with changes to nypublicradio/auth and nypublicradio/nypr-account-settings to show error messages in the password modal when a user tries to update their email.
=> Password Modal Error States

app/components/account-login-form/component.js, app/components/account-signup-form/component.js, app/validations/custom-messages.js
adds new custom message and show it
also manually rollback changest to clear errors so they don't stack up
[ticket](https://jira.wnyc.org/browse/WE-6757)
=> user disabled error messages for login and sign up

app/components/account-reset-password-form/template.hbs, app/components/account-signup-form/template.hbs
Hide the password requirements once the user has typed a valid password.
https://jira.wnyc.org/browse/WE-6804
=> WE-6816 hide clue on valid password

app/styles/_discover.scss
changes the z-index of `.sitechrome-top` in discover, so the popup (a child of `.sitechrome-top`) can be higher.
Also updates the user nav link colors in discover because it was hard to read.
https://jira.wnyc.org/browse/WE-6798
=> WE-6798 unclickable nav popout in discover

app/components/account-signup-form/component.js, app/components/account-signup-form/template.hbs
rebased version of the earlier PR
=> use nypr-ui onInput event to validate email confirmation field

app/services/session.js
some clients save browserId with quotes. make sure to clean them up
=> strip double quotes from browserId

app/components/account-login-form/component.js, app/components/account-login-form/template.hbs, app/styles/_accounts.scss, app/validations/custom-messages.js, tests/acceptance/login-test.js
When there is an email/password mismatch, show the error separate from the input fields.
Also moves a few errors into custom-messages.
https://jira.wnyc.org/browse/WE-6837
=> WE-6837 Show new login error

app/styles/_site-chrome.scss
(instead of waiting until the page is loaded), making it feel so much faster
=> Fix nav link active state so it looks active while the page is loading

app/styles/_site-chrome.scss
Some shows use a more explicit donate button so we want to make sure no matter what donate button they use, the header looks good. https://jira.wnyc.org/browse/WE-7111
=> Fix mobile header for studio 360

app/lib/alien-dom.js, app/models/django-page.js
now that we're appending instead of replacing, we need to clear out any
text content so it can be re inserted later
this is required as of #101 
[ticket](https://jira.wnyc.org/browse/WE-7078)
=> embedded components for appending

app/components/user-settings/template.hbs, app/styles/_usersettings.scss, package.json
migrated from nypublicradio/wqxr-web-client#54
=> user settings dropdown

app/lib/compat-hooks.js, app/routes/djangorendered.js, app/templates/djangorendered.hbs, app/templates/index.hbs, tests/acceptance/djangorendered-test.js, tests/acceptance/viewing-show-test.js
django pages have become useful for rendering UI components as well as
route-level "page" objects. This PR moves class tweaking to the
`djangorendered` route so that inappropriate classes aren't added to page
UI objects. This will prevent `.l-constrained` from being added to `django-page` components rendered at a deeper nested position.
=> move class name tweaking to route

app/components/user-navigation/component.js, app/components/user-navigation/template.hbs
The tricky thing here is we can't use the link-handler to track
links from data-attributes AND have an action on the link to close
the popup.
Having an action manually fire the tracking event isn't super elegant,
but we can clean this up a little when we migrate the events to GTM.
https://jira.wnyc.org/browse/WE-7080
=> Update Account and settings links to not refresh page.

app/styles/_site-chrome.scss
This addresses changing the white "Follow" header in the site chrome to gray on the inner pages.
=> wnyc social icons header override

app/controllers/reset.js, app/controllers/validate.js, app/mixins/deauthenticated-route-mixin.js, app/routes/application.js, app/routes/login.js, app/routes/reset.js, app/routes/signup.js, app/routes/validate.js, app/services/session.js, tests/acceptance/login-test.js, tests/acceptance/reset-test.js, tests/acceptance/signup-test.js, tests/acceptance/validate-test.js, tests/acceptance/verify-test.js, tests/unit/mixins/deauthenticated-route-mixin-test.js
You can only visit them while unauthenticated
If you attempt to visit while authenticated, you are redirected to the index.
If you visit these routes while authenticated, you will become unauthenticated, but remain on the route.
These routes present the user with a login form after they come in from an email, so on the off chance a user clicks a link in their email while already logged in (maybe even to a different account) we want to log them out so they can log in properly when the login form appears.
(We could be nicer and log the user out here closer to when they try to log in but I think this is rare enough that we can use a blunt tool and log them out when the route loads. And being able to using a mixin to manage this like the other types of routes is nice.)
=> WE-7083 control auth routes access

app/controllers/archive.js, app/router.js, app/routes/archive.js, app/story/adapter.js, app/story/model.js, app/story/serializer.js, app/templates/archive-loading.hbs, app/templates/archive.hbs, mirage/config.js, mirage/factories/story.js, tests/acceptance/show-archive-test.js, tests/unit/controllers/archive-test.js, tests/unit/routes/archive-test.js
[NPL-1019](https://jira.wnyc.org/browse/NPL-1019)
This PR adds an `archive` route that is primarily for producers. The goal is to help them navigate their back catalog in a way that surfaces useful metadata about their episodes, segments, and articles.
The design isn't great, but it's functional. Maybe @marineb can help out with that?
=> NPL-1019 Show Archive View

app/story/model.js, app/story/route.js, mirage/factories/story.js, tests/acceptance/listing-page-test.js, tests/acceptance/viewing-story-test.js, tests/unit/models/story-test.js, yarn.lock
wqxr is emberizing its story page, which required updates to the api. this PR modifies how the wnyc app consumes from the server without going entirely to an emberized story
=> incremental prep for emberizing story

app/styles/app.scss, app/styles/legacy/_musicians-ensemble.scss, app/styles/legacy/_schedule.scss, yarn.lock
[WE-7470](https://jira.wnyc.org/browse/WE-7470)
This copies over the `musicians-ensemble` and `schedule` sass partials from the wqxr web client.
It also bumps the hash for nypr-ui. I moved some sass mixins to a different file so we can start moving towards the idea that nypr-ui doesn't produce CSS but rather exposes SASS variables for upstream apps to use.
=> match wqxr playlist page

app/lib/alien-dom.js, config/environment.js
[WE-7525](https://jira.wnyc.org/browse/WE-7525)
also makes the selector configurable so this file can be shared as an
addon
=> WE-7525 save #fb-root from being cleared away by alien dom cleanups

app/controllers/application.js, app/story/template.hbs, app/templates/application.hbs
https://jira.wnyc.org/browse/GT-85
> - For WNYC News stories, the show name appears in the label on the "Pause" event but not on the "Played Story" event
For `listen-button` instances, we need to set `itemShow` to `headers.brand.title` when `showTitle` is not available, so that "WNYC News" is added to the button's `data-show` attribute where we can use it for GTM events.
=> GT-85 news show titles

yarn.lock
Update yarn.lock to bring in the following changes:
https://github.com/nypublicradio/nypr-metrics/pull/6  Don't fire Stream Launched event on resumes
https://github.com/nypublicradio/nypr-metrics/pull/7 Don't fire finished story event for bumpers
=> Upgrade nypr-metrics

app/channel/route.js, yarn.lock
Now using canonicalHost from the channel model in nypr-publisher-lib v0.0.5
No more unsafe pops
=> Update channel redirects

app/templates/application.hbs
Fix firefox quantum player bug by forcing the player into the correct mode and not relying on hifi to detect streaming audio.
=> Fix firefox quantum player bug by forcing the player into the correct mode

circle.yml
This updates the build to circle ci 2.0
There are 3 jobs, which run in sequence: `build`, `test`, `deploy`.
The `build` job installs all the global and local node dependencies. We don't need to manually install yarn anymore on circle 2.0.
=> Updates to circle 2.0

circle.yml, testem.js
Enables this tab in the Circle CI build page:
https://circleci.com/gh/nypublicradio/wnyc-web-client/1686
Also adds an .xml test report with individual test timings to the circle artifacts folders.
Local testing should remain unaffected by this change.
=> Add xml report output in circle ci to test config

app/channel/route.js, app/channel/template.hbs, mirage/config.js, package.json, tests/acceptance/data-layer-test.js, tests/acceptance/listing-page-test.js, tests/acceptance/paginating-listing-page-test.js, yarn.lock
For compatibility with publisher#369, this PR updates the web client to do a direct store request for a `channel`, aka `listing-page` aka `CrossChannel` object from publisher.
This has two advantages:
1. Move away from depending on the `django-page` component for rendering, slightly improving performance
2. No longer requiring embedded raw JSON text on the initial request for loading up data. This technique proved fragile and error-prone. Show pages should stop dying due to embedded script tags in text fields now.
[ticket](https://jira.wnyc.org/browse/RT-658)
=> channel route migration

app/helpers/append-query.js, app/templates/index.hbs, tests/integration/helpers/append-query-test.js
[ticket](https://jira.wnyc.org/browse/RT-757)
this adds an append-query helper to catch any weird edge cases when adding query strings to a given url. maybe the url already ends in a `?`. maybe the url already has query params, etc.
=> Gothamist UTM params

app/components/site-chrome/site-footer/template.hbs
Replaces the intermediary /audio/podcasts/ redirect URL in favor of a direct link to wnycstudios.org.
=> RT-908 change footer podcast link

app/story/template.hbs
Needs to go on the header.share component and not the buttons themselves.
=> Adds a via param to the story header share buttons

package.json, yarn.lock
This PR just bumps the `nypr-publisher-lib` version in the wnyc web client in order to get non-playlist streams listed on wnyc.org/streams. But it's a significant version jump that seems to have also prompted an upgrade to `nypr-audio-services`, so I wanted to flag it.
=> bump nypr-publisher-lib version MT-91

app/models/order.js
- Add isPayment field to order model. This is currently an actively and correct field returned by nF and used in the member-center. Member Center is not reporting accurate gift/payment history because of the omission of this field.
- Further work to be done in repo: nypr-account-settings to correct member center display errors
=> Add isPayment attribute to order model

.gitignore, app/templates/index.hbs
Small update that changes the size mapping for wnyc_leaderboard to put the 970x90 and 970x415 under one `array`, rather than passing them as individual arguments
=> Update wnyc_leaderboard size mapping

app/styles/_stream-widget.scss
Some of the titles inn the stream banner were getting their text colored black due to a conflicting css rule from the home page that was trying to make all h2s on the home page colored black.
=> SUP- 5991 Color h2 text white in the stream banner card

app/components/site-chrome/template.hbs
While QAing the merch store link I noticed we needed an extra space between the word "Shop" and the external link indicator.
QA link for the last pull request was here:  https://wnyc.demo2.wnyc.net/?build=wnyc/sguzik-merch-store
=> Adding a space

app/components/centennial/centennial-nav/component.js, app/components/centennial/centennial-nav/template.hbs, app/styles/_centennial.scss, app/styles/centennial/_centennial-base.scss, app/styles/centennial/_centennial-header.scss, app/styles/centennial/_centennial-nav.scss, app/templates/centennial.hbs, tests/integration/components/centennial/centennial-nav/component-test.js
https://nypublicradio-digital.atlassian.net/browse/FE-132
=> FE-132 Add centennial in-page nav

app/channel/template.hbs, app/styles/_newsounds.scss, app/styles/app.scss
Per https://nypublicradio-digital.atlassian.net/browse/ACMS-474 and internal discussions, this PR makes a few template and CSS updates to the WNYC web client to support the New Sounds show pages on WNYC.org. There's a slug added to the channel template in order to target New Sounds specific styles to three show pages.
Given plans to replatform this site this year, the CSS was done in a pretty fast and loose way. It's not future-proof, but that should be OK for this short-term context.
=> Adds New Sounds styles to WNYC.org
